name: branch08

services:

  kafka:
    image: confluentinc/cp-kafka:8.0.1
    container_name: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - CLUSTER_ID=4L6g3nShT-eMCtK-b08Zsw
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=branch01
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_1_NAME=branch02
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_2_NAME=branch03
      - KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_3_NAME=branch04
      - KAFKA_CLUSTERS_3_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_4_NAME=branch05
      - KAFKA_CLUSTERS_4_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_5_NAME=branch06
      - KAFKA_CLUSTERS_5_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_6_NAME=branch07
      - KAFKA_CLUSTERS_6_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_7_NAME=branch08
      - KAFKA_CLUSTERS_7_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  order-service:
    build: branch08_consumer_configuration/order-service
    container_name: order-service-b08
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  notification-service-1:
    build: branch08_consumer_configuration/notification-service
    container_name: notification-service-1-b08
    ports:
      - "8082:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INSTANCE_ID=notification-1
    depends_on:
      kafka:
        condition: service_healthy

  notification-service-2:
    build: branch08_consumer_configuration/notification-service
    container_name: notification-service-2-b08
    ports:
      - "8083:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INSTANCE_ID=notification-2
    depends_on:
      kafka:
        condition: service_healthy

networks:
  default:
    external: true
    name: kafka-lab