security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/etc/kafka/secrets/certs/kafka.server.truststore.jks
ssl.truststore.password=kafkalab-ssl-secret
ssl.endpoint.identification.algorithm=