server:
  port: 8103

spring:
  application:
    name: analytics-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "OrderCreatedEvent:com.kafkalab.analytics.model.OrderCreatedEvent"